loaderVersion = "${loader_version_range}"
modLoader = "${loader_name}"
license = "${mod_license}"
[[mods]]
displayName="${mod_name}"
modId = "${mod_id}"
version = "${mod_version}"
description='''${mod_description}'''

${mixins_block}

[[dependencies.${mod_id}]]
mandatory = true
modId = "${loader_mod_name}"
ordering = "NONE"
side = "BOTH"
versionRange = "${loader_version_range}"
[[dependencies.${mod_id}]]
mandatory = true
modId = "minecraft"
ordering = "NONE"
side = "BOTH"
versionRange = "${minecraft_version_range}"
[[dependencies.${mod_id}]]
modId="bookshelf"
type="required"
versionRange="[20.2.13,]"
ordering="NONE"
side="BOTH"
