loaderVersion = "${loader_version_range}"
modLoader = "${loader_name}"
license = "${mod_license}"
[[mods]]
displayName="${mod_name}"
modId = "${mod_id}"
version = "${version}"
description='''${mod_description}'''

${mixins_block}

[[dependencies.${mod_id}]]
mandatory = true
modId = "${loaer_mod_name}"
ordering = "NONE"
side = "BOTH"
versionRange = "${loader_version_range}"
[[dependencies.${mod_id}]]
mandatory = true
modId = "minecraft"
ordering = "NONE"
side = "BOTH"
versionRange = "${mc_version_range}"
