license = "${mod_license}"
loaderVersion = "${forge_version_range}"
modLoader = "javafml"
[[mods]]
description = '''${mod_description}'''
displayName = "${mod_name}"
modId = "${mod_id}"
version = "${version}"

${mixins_block}

[[dependencies.${mod_id}]]
mandatory = true
modId = "forge"
ordering = "NONE"
side = "BOTH"
versionRange = "${forge_version_range}"
[[dependencies.${mod_id}]]
mandatory = true
modId = "minecraft"
ordering = "NONE"
side = "BOTH"
versionRange = "${mc_version_range}"
